### ISSUE TITLE
Staging bugs ticket

### ISSUE THREAD

**Issue by AlexandreG-tech** [OfflineHQ/marketplace#117]

**Comment by AlexandreG-tech** [comment]
High Priority :
- [x] Infinite loop between cart and cart/purchase when eventPassOrder is confirmed
- [x] Stripe checkout.session.complete -> checkout.session.complete**d**
- [x] Cannot purchase 
![image](https://github.com/Offline-Project/marketplace/assets/141121647/67da16ac-7354-445d-85d5-2fa6f80233bc)

- [x]  Cannot purchase after Sumsub is done, still asking me to verify (must be linked to double account)
![image](https://github.com/Offline-Project/marketplace/assets/141121647/50831cbf-d275-488d-85c4-ee9963874045)
- [x] organizer/slug/event/slug/purchase route fail and so it's impossible to choose pass to make an eventPassPendingOrder
![image](https://github.com/Offline-Project/marketplace/assets/141121647/3440870b-c2a3-4b72-bccd-9ea1f99dbc02)
- [x] Thirdweb claim seems to be making the webhook timeout https://dashboard.stripe.com/test/webhooks/we_1NyAYfLOVl3N7zqJy746Y5zS but Nfts are send correctly https://thirdweb.com/goerli/0xc0B39286805E907f35a6734033813Aa7624E508E/events



Medium Priority :
- [x] Multiple account creation due to cookies ?

**Comment by AlexandreG-tech** [comment]
- [x] Image not resize for Event cf. https://www.staging.offline.live/fr/organizer/fifa/event/fifa-deutschland-10-jahre-spaeter
- [x] Clicking on organizer on Event display shows a not found

**Comment by sebpalluel** [comment]
> * Clicking on organizer on Event display shows a not found

Not a bug, just no Organizer page for now, waiting for specs

**Comment by sebpalluel** [comment]
- [x] add a global good looking NotFound component
- [x] add a global good looking Error component
- [x] add specific Error component for each sections

**Comment by sebpalluel** [comment]
> * Image not resize for Event cf. https://www.staging.offline.live/fr/organizer/fifa/event/fifa-deutschland-10-jahre-spaeter

Not a bug, this a standard format for Avatar (square). So the src image should be in the square format with FIFA centered in the middle for it to render. Also image should be on svg format with transparent background to enhanced it visually.
